name: First Workflow

on: 
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print HI
        run: echo "HI!!!!!!!!!!!!!!"

      - name: Print bye
        run: echo "BYE"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "HELLO WORLD"
