name: first-workflow
on: push
jobs:
 first-job:
  runs-on: ubuntu-latest
  steps:
   - name: Print Greetings
     run: echo "HII HELLLOOO"
   - name: Print Goodbye
     run: echo "SEE YOU SOON!!!"
  second-job:
   runs-on: ubuntu-latest
  steps: 
   - name: Print Hello World
     run: echo "HELLO WORLD!!"
  
