name: Print Hello
on: push
jobs:
 first-job :
  runs-on: ubuntu-latest
  steps:
    - name: Print Greetings
      run: echo "HI HOW ARE YOU??"
    - name: Print bye
      run: echo "GOODBYE"
 second-job:
   runs-on: ubuntu-latest
   steps:
    - name: Print Hello World
      run: echo "HELLO WORLD"
  
     
  
