name: Custom Environmnet Variables
on: push
env: 
 SUBSCRIBE: "SUPERMAN"
jobs: 
   hello:
    runs-on: ubuntu-latest
    env: 
      MEMORY: TOKYO
    steps:
      - name: memory check
        run: echo "$MEMORY"
        env: 
          NAME: "HINAGURA"
      - name: Name Check
        run: echo "$NAME"
        
