name: Print Greetings
on: push
jobs:
 first-job:
  runs-on: ubuntu-latest
  steps:
    - name: Print Greetings
      run: echo "HIII HELLOOOO HOW ARE YOU"
    - name: Print Goodbye
      run: echo "SEE YOU SOON!!!"
 second-job:
  runs-on: ubuntu-latest
  steps: 
    - name: Print Hello World
      run: echo "HELLO WORLD"
