name: Action_Workflow
on: [push]
jobs: 
 job-01:
    runs-on: ubuntu-latest
    steps: 
      - name: List Files
        run: |
         pwd
         ls -a
         echo "$GITHUB_SHA"
         echo "$GITHUB_ACTOR"
         echo "$GITHUB_REPOSITORY"
